site_name: Jesus' Disciples Song Book

theme:
  name: material

plugins:
  - search

nav:
  - Home: index.md

  - English Songs:
      - O The Spirit Filled Life: english/O-The-Spirit-Filled-Life.md

  - Telugu Songs:
